trigger:
  - main

pool:
  name: ClassLibrary  # Your self-hosted agent pool

stages:
  - stage: Build
    jobs:
      - job: BuildApp
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'

          - script: dotnet restore ShowCase/ShowCase.csproj

          - script: dotnet build ShowCase/ShowCase.csproj --configuration Release

          - script: dotnet publish ShowCase/ShowCase.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
              ArtifactName: 'webapp'
              publishLocation: 'Container'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployApp
        steps:
          - download: current
            artifact: webapp

          - script: |
              echo "Deploying app to local machine..."
              cd $(Pipeline.Workspace)/webapp
              dotnet ShowCase.dll
            displayName: 'Run ASP.NET Core app locally'
